content/blog/review-challenge-010.md

Please edit as you see fit. Thank you.

Add weekly review challenge #010

---

content/blog/review-challenge-011.md

Feel free to edit as please. Thanks.

Add Review for Challenge #011

---

content/blog/review-challenge-012.md

Add weekly review challenge #012

---

content/blog/review-challenge-013.md

Add weekly challenge review week #013

---

content/blog/review-challenge-014.md

Added weekly review 014

---

content/blog/review-challenge-015.md

Feel free to edit as fit. Thanks.

Add Perl Weekly Challenge Review 015

---

content/blog/review-challenge-016.md

Added weekly review for challenge 016

---

content/blog/review-challenge-017.md

Added weekly review for Perl Weekly Challenge 017

---

content/blog/review-challenge-018.md

Added weekly review 018

---

content/blog/review-challenge-019.md

Feel free to edit it. Thanks. ;-)

Add weekly challenge review 019

---

data/faq.yml

Improve some of the language.

---

content/blog/review-challenge-020.md

Add weekly challenge review 020

---

content/blog/review-challenge-021.md

Add weekly review 021

---

content/blog/review-challenge-022.md

Add weekly perl 5 review 022

---

content/blog/review-challenge-023.md

Add weekly perl 5 review 023

---

content/blog/review-challenge-024.md

Add weekly review 024

---

content/blog/review-challenge-025.md

Add weekly review 025

---

content/blog/review-challenge-026.md

Add weekly review 026

---

content/blog/review-challenge-027.md

Add weekly review 027

---

content/blog/review-challenge-028.md

Add weekly review 028

---

content/blog/review-challenge-029.md

Add weekly review 029

---

content/blog/review-challenge-030.md

Add weekly review 030

---

content/blog/review-challenge-031.md

Add weekly review 31

---

content/blog/review-challenge-032.md

Add weekly review 032

---

content/blog/review-challenge-033.md

Add weekly review 033

---

content/blog/review-challenge-034.md

Add weekly review #34

---

content/blog/review-challenge-035.md

Add weekly review 035

---

themes/timer-hugo/layouts/404.html
themes/timer-hugo/layouts/partials/about.html
themes/timer-hugo/layouts/partials/cta.html
themes/timer-hugo/layouts/partials/header.html

* Removed an invalid <meta> element
* Made some header start and end tags match

Fixed some HTML validity errors

---

content/blog/review-challenge-036.md

Add weekly review 036

---

content/blog/perl-weekly-challenge-038.md

Prefix is prepended rather than appended

Fix formulation of task 1

---

content/blog/review-challenge-037.md

Add weekly review 037

---

content/blog/review-challenge-038.md

Feel free to edit it. Thanks. ;-)

Add weekly review 038

---

content/blog/review-challenge-039.md

Feel free to edit it. Thanks. ;-)

Add weekly review 039

---

content/blog/perl-weekly-challenge-001.md
data/challenges.yml
static/css/main.css
themes/timer-hugo/layouts/partials/challenges.html

This PR contains a complete replacement for the Challenges page, as discussed via email.

New Challenges layout, data and stylesheet

---

content/blog/review-challenge-044.md

Here's the week 044 review. A few notes:
1. You may wish to set the `date:` accordingly. I'd have done so, but I don't know when you're going to publish it.
2. I left the `image:` blank this week. I suggest that having no image is much better than having an irrelevant and squashed image. But if you want to change it, I can't stop you. :-)
3. Whitespace should be more to your liking. If there is whitespace within code blocks, I left it there on purpose.

rjt's Perl review 044

---

content/blog/review-challenge-046.md

Supplying my own `image:` again this week, which is from http://www.ry.ca/2020/02/500-doors/

rjt's Perl review 046

---

content/blog/p6-review-challenge-046.md

Custom `image:` again this week.

Week 046 Raku review

---

content/blog/p6-review-challenge-047.md

1. Updated review of Arne's Task 1 solution upon receipt of new code.
2. Added review of Laurent's Task 2 one-liner that I overlooked originally.

Updated review

---

content/blog/p6-review-challenge-046.md
content/blog/review-challenge-046.md
static/css/main.css
themes/timer-hugo/layouts/partials/header.html

My script forgot to prepend the base URL to the github links. Fixed now.

Fix solution links (thanks Duane P. for noticing)

---

content/blog/review-challenge-049.md

Belated Week 049 Perl review

---

content/blog/review-challenge-054.md

I would appreciate if this could be merged and released with the Week 056 challenge in a few hours.

RJT's Week 054 Perl Review

---

content/blog/review-challenge-052.md
content/blog/review-challenge-053.md
content/blog/review-challenge-054.md

- Cheok Yin › Correct pronouns
- Laurent 053#1 › NxN, not 3x3
- Jaldhar › Add blog links my script missed (more to come later)
- Jaldhar 054#1 › Update review based on info from blog post

Fix errata

---

content/blog/p6-review-challenge-071.md

The youtube link for task 2 is currently pointing to the task 1 video.

Fix link to youtube video for task 2

---

content/blog/perl-weekly-challenge-080.md
docs/blog/perl-weekly-challenge-080/index.html

Probably a leftover from the previous week.

Fix typo in the task name

---

content/blog/perl-weekly-challenge-004.md

Hey Mohammad,
I'm just going through the old challenges and came across this. So I figured I'd suggest a fix.
Kind regards.

fix typo in description for challenge-004

---

data/team.yml

This is all the same person. There is another entry for him in line 924.
@kaicb97 can you confirm that please?

- Removed duplicate entries in Teams data

---

content/blog/meet-the-champion-038.md
docs/blog/meet-the-champion-038/index.html

I noticed a few grammar and formatting issues in my "meet the champion" text. No changes to what I actually said.

Grammar and formatting, in my own words. :-)

---

content/blog/perl-weekly-challenge-141.md

The link was not working due to a superfluous quotation mark.

Fix link to blog post by Dave Jacoby

---

content/blog/perl-weekly-challenge-153.md

Good Morning @manwar
Noticed and fixed to little typos in the current challenge.

Wk 153 typo fixes

---

content/blog/perl-weekly-challenge-154.md

The blog posts by Dave was in the list twice. Once in position 7 and once in position 9

Remove duplicated entry in blogs

---

content/blog/review-challenge-164.md

rjt's week 164 Perl review

---

content/blog/perl-weekly-challenge-200.md

Truth table won't work otherwise.

Remove errant space in @truth table

---

content/blog/guest-contribution.md
content/blog/perl-weekly-challenge-225.md

This PR fixes a number in example 3 of challenge 225. The PR also updates a link in challenge 224.

Fix example 3 in challenge 225

---

content/blog/perl-weekly-challenge-287.md
docs/blog/perl-weekly-challenge-287/index.html

aaaaa > replace aaAaa > insert aaAaa0

Fix the answer for 287/1
